use_frameworks!

target 'openLibraryThreeTestDemo_Example' do
  pod 'openLibraryThreeTestDemo', :path => '../'

  target 'openLibraryThreeTestDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
